spring.application.name=backend

spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
feign.client.config.default.loggerLevel=fulllogging.level.com.discog.backend.client.SpotifyApiClient=DEBUG